//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_objects")]
pub struct Model {
    #[sea_orm(unique)]
    pub id: Uuid,
    pub created_on: DateTimeWithTimeZone,
    pub filename: Option<String>,
    pub size_bytes: Option<i64>,
    pub upload_id: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub parts: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_object_associations::Entity")]
    FileObjectAssociations,
}

impl Related<super::file_object_associations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileObjectAssociations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
