//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_object_associations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub iterator: i32,
    pub input_object_id: Uuid,
    pub submission_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_objects::Entity",
        from = "Column::InputObjectId",
        to = "super::file_objects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FileObjects,
    #[sea_orm(
        belongs_to = "super::submissions::Entity",
        from = "Column::SubmissionId",
        to = "super::submissions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Submissions,
}

impl Related<super::file_objects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileObjects.def()
    }
}

impl Related<super::submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
