//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::file_object_associations::Entity as FileObjectAssociations;
pub use super::file_objects::Entity as FileObjects;
pub use super::services::Entity as Services;
pub use super::submissions::Entity as Submissions;
